name: "release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Image
        with:
          github-push-secret: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: automl-container
          docker-image-tag: ${{github.ref_name}}